### ISSUE TITLE
Cannot test sending a Photo

### ISSUE THREAD

**Issue by janwytze** [LasterAlex/teloxide_tests#26]
**What went wrong:**
When testing sending an photo, the test panics.

**To Reproduce:**
Run this code
```rust
    #[tokio::test]
    async fn test_bugjes() {
        let handler_tree = dptree::entry()
            .branch(
                Update::filter_message()
                    .endpoint(|bot: Bot, msg: Message| async move {
                        // Download random image.
                        let img = reqwest::get("https://picsum.photos/200/300")
                            .await
                            .unwrap()
                            .bytes()
                            .await?;

                        bot.send_photo(msg.chat.id, InputFile::memory(img))
                            .await?;

                        Ok(())
                    })
            );
        let msg = MockMessageText::new().text("/pizza");
        let bot = MockBot::new(msg, handler_tree);

        bot.dispatch().await;

        let responses = bot.get_responses();
        let message = responses.sent_messages.last().unwrap();

        assert!(message.photo().is_some());
    }

```
Expected result is a working test.
But this code returns:
```
Something went wrong and the bot panicked!
thread 'actix-server worker 0' panicked at /home/jw/.cargo/registry/src/index.crates.io-6f17d22bba15001f/teloxide_tests-0.2.0/src/server/routes/mod.rs:238:47:
called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 0, error_len: Some(1) }
```

**Additional context:**

Error occurs here:  
https://github.com/LasterAlex/teloxide_tests/blob/6e0086a76f88e8450d59e89da519cecdc605669a/teloxide_tests/src/server/routes/mod.rs#L239

It seems to expect an utf8 string, but it receives an image:
```
called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 0, error_len: Some(1) }
``` 

**Meta:**
`teloxide_tests` version: __0.2.0__
`teloxide` version: __0.13.0__

**Comment by LasterAlex** [comment]
Replicated, will fix shortly on the `latest-teloxide` branch.

**Comment by LasterAlex** [comment]
It is weird that it happens, but for now please use

```toml
teloxide = { git = "https://github.com/teloxide/teloxide.git", rev = "94db1757dc96116f4756a586fcbce3ac5ebd0c59", features = ["macros"] }
teloxide_tests = { git = "https://github.com/LasterAlex/teloxide_tests.git", branch = "latest-teloxide" }
```

(teloxide version has to be exactly that)
